const menus = [{
	icon:require('themes/images/menu/warning.png'),
	name:'一键报警',
  route:'warning'
}
,{
    icon:require('themes/images/menu/location.png'),
    name:'地理定位',
    route:'position'
}
  ,{
    icon:require('themes/images/menu/route.png'),
    name:'巡逻路线',
    route:'route'
  }
  ,{
    icon:require('themes/images/menu/notice.png'),
    name:'平台通知',
    route:'notice'
  }
  ,{
    icon:require('themes/images/menu/task.png'),
    name:'任务处理',
    route:'task'
  }
 ,{
    icon:require('themes/images/menu/tour.png'),
    name:'旅游阿拉善',
    route:'tour'
 }
  ,{
    icon:require('themes/images/menu/patry.png'),
    name:'党建阿拉善',
    route:'patry'
  }
  ,{
    icon:require('themes/images/menu/convenient.png'),
    name:'民生阿拉善',
    route:'convenient'
  }
  ,{
    icon:require('themes/images/menu/ecology.png'),
    name:'生态阿拉善',
    route:'ecology'
  }
  ,{
    icon:require('themes/images/menu/books.png'),
    name:'书香阿拉善',
    route:'books'
  }
]

export default menus
